#!/bin/bash
for a in `seq 0 10 100`
do
./transcooling $a <cloud.dat > e3-$a.out
gnuplot <<- EOF
set term gif
set out "vel${a}.gif"
plot [-0.5:0.5][-0.5:0.5] "e3-$a.out" u 6:7 t 't=$a'
EOF
gnuplot <<- EOF
set term gif
set out "space${a}.gif"
plot [-1000:1000][-1000:1000] "e3-$a.out" u 3:4 t 't=$a'
EOF
done
convert vel?.gif vel??.gif vel???.gif -delay 80 -loop 0 Velocity.gif
rm vel*.gif
convert space?.gif space??.gif space???.gif -delay 80 -loop 0 Space.gif
rm space*.gif
#rm e3-$a.out
